# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RSSHUB_CUSTOM_ADDR: http://82.157.186.108:1200
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      id: setup-python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: setup poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: cache dependencies
      id: cache-dependencies
      uses: actions/cache@v3
      with:
        path: |
          .venv
        key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-poetry-${{ hashFiles('poetry.lock') }}
    - name: Install dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: |
        poetry install
    - name: weibo
      run: |
        poetry run python3 weibo.py
    - name: zhihu
      run: |
        poetry run python3 zhihu.py
    - name: rss
      run: |
        poetry run python3 rss.py
